root: true
extends:
  - eslint:recommended
  - plugin:react-hooks/recommended
  - plugin:@typescript-eslint/strict-type-checked
  - plugin:@typescript-eslint/stylistic-type-checked
plugins:
  - react-hooks
  - prefer-arrow
parser: '@typescript-eslint/parser'
env:
  browser: true
  node: true
  es2022: true
parserOptions:
  project: true
rules:
  no-mixed-operators: error
  react-hooks/rules-of-hooks: error
  react-hooks/exhaustive-deps: warn
  no-unused-vars: 'off'
  '@typescript-eslint/no-unused-vars':
    - error
    - argsIgnorePattern: ^_
  # https://github.com/mobu-of-the-world/mobu/pull/82#discussion_r606832062
  # https://github.com/mobu-of-the-world/mobu/pull/476#discussion_r907948539
  prefer-arrow/prefer-arrow-functions:
    - error
    - disallowPrototype: true
      singleReturnOnly: false
      classPropertiesAllowed: false
      allowStandaloneDeclarations: false
  no-restricted-syntax:
    - error
    - selector: TSEnumDeclaration
      message: >-
        Don't declare enums. ref: https://www.kabuku.co.jp/developers/good-bye-typescript-enum
  # See https://zenn.dev/teppeis/articles/2023-04-typescript-5_0-verbatim-module-syntax for enabling reason
  '@typescript-eslint/consistent-type-imports': 'error'
  '@typescript-eslint/no-import-type-side-effects': 'error'
overrides:
  - files:
      - src/**/*.ts
    rules:
      '@typescript-eslint/prefer-readonly-parameter-types':
        - error
        - ignoreInferredTypes: true
  - files:
      - src/**/*.test.ts
    rules:
      '@typescript-eslint/no-floating-promises':
        - off
